apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-db-pvc
  namespace: {{ .Values.namespace }} 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
