apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer  # Utilise NodePort pour exposer Nginx via un port spécifique sur chaque nœud
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8081  # Le port sur lequel le service écoute
      targetPort: 8081  # Le port où Nginx écoute dans le conteneur
      #nodePort: 30081  # Le port externe sur lequel Nginx sera accessible (port dans la plage 30000-32767)
