apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: {{ .Values.namespace }} 
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8000
  selector:
    app: movie-service
  type: ClusterIP
